---
title: "Bolt Action"
author: "Dirk Aumueller"
date: last-modified
date-format: "DD.MM.YYYY"
lang: "en"
---

## Australians

Primer: Vallejo Polyurethane Black Primer

### Infantry

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Helmet | VMC Olive Grey 70.888 | GW Athonian Camoshade | VMC Russian Uniform 70926 | VMC Green Grey |  |
| Boots | GW Rhinox Hide | GW Agrax Earthshade | GW Doombull Brown |  |  |
| Uniform | Russian Uniform | GW Athonian Camoshade | VMC Russian Uniform 70926 | VMC Green Grey 70886 | VMC Green Grey 70886 & VMC Deck Tan (50/50) |
| Metal | VMC German Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Straps, Backpacks, Bags | VMC Khaki | GW Agrax Earthshade | VMC Khaki | VMC Iraqui Sands |  |
| Flesh | Foundry Mediterranean Flesh (Shade) | GW Reikland Flesh  | Foundry Mediterranean Flesh (Shade) | Foundry Mediterranean Flesh | Foundry Mediterranean Flesh (Light) | GW Kislev Flesh |
| Drinking Bottle | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown | GW Tuskor Fur |  |
| Drinking Bottle Metal Part, Knife | VMC Dark Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Weapon | VMC Dark Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Poncho | VMC Luftwaffe Cam. Green | GW Athonian Camoshade | VMC Luftwaffe Cam. Green | VGC Goblin Green |  |
| Knife Sheath | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark | GW Gorthor Brown |  |

### Mathilda II Tank

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Primer | Vallejo Polyurethane Black Primer |  | Daler Rowney FW Ink White |  |  |  |
| Base Color | VMC Russian Uniform 70.924 |  | VMC Deck Tan & VMC Russian Uniform (90/10) |  |
| Camouflage | VMC VMC Olive Grey 70.888 |  | VMC Deck Tan & VMC Russian Uniform (90/10) |  |
| Wood | VMC Flat Brown 70.984 | GW Agrax Earthshade |  |  |
| Metal | VGA Chainmail Silver 72.753 | GW Nuln Oil |  |  |
| Blanket | VMC British Uniform 70.921 | GW Agrax Earthshade | VMC British Uniform 70.921 | VMC British Uniform 70.921 & VMC Deck Tan 70.874 (50/50) | VMC Deck Tan 70.874 |
| Belt | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & GW Gorthor Brown (50/50) | GW Gorthor Brown |
| Chipped Paint | Bleached Bone |  |  |  |
| Pin & Panel Wash | Mig Nato Camouflages Wash |  |  |  |
| Weathering | AK Streaking Grime |  |  |  |
| Dirt | Pigmente Mischung von Vallejo |  |  |  |

### Bases

| ITEM | BASE | HIGHLIGHT I | HIGHLIGHT II |
| --- | --- | --- | --- |
| Earth | Vallejo Dark Earth Texture | GW Zandri Dust | Vallejo Iraqui Sand |
| Baserand | Schwarz |  |  |
| Tufts |  |  |  |
| Stones | Vallejo Basalt Grey | Vallejo Model Air Pale Grey | Vallejo Model Air White |
