build:
  stage: build
  image:
    name: rocker/tidyverse:latest
  script:
  - sed -i "s|__ci_commit_tag__|${CI_COMMIT_TAG:-wip}|g" painting-guide.qmd
  - sed -i "s|__ci_commit_short_sha__|${CI_COMMIT_SHORT_SHA}|g" painting-guide.qmd
  - apt-get update
  - apt-get install -y libgtk-4-1 fonts-liberation libasound2t64 libatk1.0-0 libatspi2.0-0 libnspr4 libnss3 libxcomposite1 xdg-utils libatk-bridge2.0-0
  - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb
  - apt --fix-broken install -y
  - dpkg -i google-chrome-stable_current_amd64.deb
  - quarto install --no-prompt tinytex
  - quarto install --no-prompt extension lukfor/quarto-eisvogel
  - quarto render painting-guide.qmd --to eisvogel-pdf

  artifacts:
    paths:
    - painting-guide-${CI_COMMIT_TAG:-wip}.pdf
