---
title: "Painting Guide"
subtitle: "__ci_commit_tag__, __ci_commit_short_sha__"
author: "Dirk Aumueller"
date: last-modified
date-format: "DD.MM.YYYY"
lang: "de"
format:
  eisvogel-pdf:
    pdfengine: xelatex
    titlepage: true
    titlepage-text-color: "ffffff"
    titlepage-color: "0064a5"
#    titlepage-logo: images/logo.png
    titlepage-rule-color: "ffffff"
    header-right: ""
    toc: true
    toc-own-page: true
    number-sections: false
    listings-no-page-break: true
    code-block-font-size: \scriptsize
    output-file: painting-guide-__ci_commit_tag__.pdf
---

## Introduction

This document is a loose collection of my painting steps for various tabletop games and their miniatures and scenery.

## Alien vs. Predator

### Alien Stalker

1. Airbrush the miniature with Vallejo Black primer.
2. Airbrush Tamiya XF-9 Hull Red with 45° angle one the miniature leaving deeper recesses black.
3. Airbruh Tamiya XF-68 Nato Brown on the head.
4. Wash entire miniature with a mix of 50/50 GW Badab Black and water.
5. Drybrush highlights with Vallejo Mahogany Brown (VJ70846).
6. Wash entire miniature with a mix of 20/80 GW Badab Black and water.

### Alien Infant

1. Airbrush the miniature with Vallejo black primer.
2. Drybrush the miniature with GW Mithril Silver. Paint the head completely with this color.
3. Wash entire miniature with a mix of 50/50 GW Badab Black and water. If still to shiny, repeat washing.
4. Fade head at the back with Vallejo Negro Black (VJ70950).
5. Wash entire miniature with a mix of 50/50 GW Badab Black and water. If still to shiny, repeat washing.
Predator

### USCM

1. Airbrush the miniature with Vallejo Black primer.
2. Airbrush clothes and skin with a light layer of Vallejo Grey primer.
3. Paint the uniform with Vallejo German Camouflage Beige (VJ70821).
a. Paint camouflage pattern with Vallejo German Camouflage Medium Brown (VJ70826), Luftwaffe Camouflage Green (VJ70823) and Deck Tan (VJ70986).
4. Paint the armor including ammunition pouches with Vallejo German Camouflage Dark Green (VJ70979).
5. Paint flesh with Games Workshop Tallarn Flesh.
6. Use Deck Tan (VJ70986) for all white-like colors.
7. Straps are Vallejo German Camouflage Beige (VJ70821) painted.
8. Flashlights, cameras, displays, head on displays, etc. are painted with Vallejo Ultramarine Blue (VJ72022).
9. Weapons, boots and armor straps stay black.
10. Wash entire model with Games Workshop Devlan Mud.
11. Highlight each color with base color, sometimes add some Vallejo Deck Tan (VJ70986).
12. Highlight weapons and black armor straps with Vallejo German Grey (VJ70995).

### Bases

1. Apply Vallejo Dark Earth (VJ26218) to base.
2. Drybrush base with Vallejo Bone White (VJ72034).

## Bolt Action

### Australians

Primer Vallejo Polyurethane Black Primer

### Infantry

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Helmet | VMC Olive Grey 70.888 | GW Athonian Camoshade | VMC Russian Uniform 70926 | VMC Green Grey |  |
| Boots | GW Rhinox Hide | GW Agrax Earthshade | GW Doombull Brown |  |  |
| Uniform | Russian Uniform | GW Athonian Camoshade | VMC Russian Uniform 70926 | VMC Green Grey 70886 | VMC Green Grey 70886 & VMC Deck Tan (50/50) |
| Metal | VMC German Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Straps, Backpacks, Bags | VMC Khaki | GW Agrax Earthshade | VMC Khaki | VMC Iraqui Sands |  |
| Flesh | Foundry Mediterranean Flesh (Shade) | GW Reikland Flesh  | Foundry Mediterranean Flesh (Shade) | Foundry Mediterranean Flesh | Foundry Mediterranean Flesh (Light) | GW Kislev Flesh |
| Drinking Bottle | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown | GW Tuskor Fur |  |
| Drinking Bottle Metal Part, Knife | VMC Dark Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Weapon | VMC Dark Grey | GW Nuln Oil | VMC Basalt Grey | VMC Basalt Grey & VMC Deck Tan (50/50) |  |
| Poncho | VMC Luftwaffe Cam. Green | GW Athonian Camoshade | VMC Luftwaffe Cam. Green | VGC Goblin Green |  |
| Knife Sheath | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark | GW Gorthor Brown |  |

### Mathilda II Tank

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Primer | Vallejo Polyurethane Black Primer |  | Daler Rowney FW Ink White |  |  |  |
| Base Color | VMC Russian Uniform 70.924 |  | VMC Deck Tan & VMC Russian Uniform (90/10) |  |
| Camouflage | VMC VMC Olive Grey 70.888 |  | VMC Deck Tan & VMC Russian Uniform (90/10) |  |
| Wood | VMC Flat Brown 70.984 | GW Agrax Earthshade |  |  |
| Metal | VGA Chainmail Silver 72.753 | GW Nuln Oil |  |  |
| Blanket | VMC British Uniform 70.921 | GW Agrax Earthshade | VMC British Uniform 70.921 | VMC British Uniform 70.921 & VMC Deck Tan 70.874 (50/50) | VMC Deck Tan 70.874 |
| Belt | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & GW Gorthor Brown (50/50) | GW Gorthor Brown |
| Chipped Paint | Bleached Bone |  |  |  |
| Pin & Panel Wash | Mig Nato Camouflages Wash |  |  |  |
| Weathering | AK Streaking Grime |  |  |  |
| Dirt | Pigmente Mischung von Vallejo |  |  |  |

#### Bases

| ITEM | BASE | HIGHLIGHT I | HIGHLIGHT II |
| --- | --- | --- | --- |
| Earth | Vallejo Dark Earth Texture | GW Zandri Dust | Vallejo Iraqui Sand |
| Baserand | Schwarz |  |  |
| Tufts |  |  |  |
| Stones | Vallejo Basalt Grey | Vallejo Model Air Pale Grey | Vallejo Model Air White |

## Epic Armageddon

### Steel Legion Infantry

| PART | COLOR |
| --- | --- |
| Primer | Vallejo Grey Primer |
| Uniform | GW Contrast Aggaros Dunes |
| Helmet, Trousers, Belt | GW Contrast Black Templar |
| Boots, ABC Mask | GW Contrast Wyldwood |
| Lasguns | GW Blood Angels Red |
| Metal | Vallejo Game Air Chainmail Silver |
| Rocket Launcher Grenades | GW Contrast Militarum Green |

### Imperial (Un-)Armored Vehicles

| PART | COLOR |
| --- | --- |
| Primer | Vallejo Grey Primer |
| Camouflage Light | Ammo of Mig RAL7028 Dunkelgelb '44 |
| Camouflage Green | Tamiya XF-58 |
| Metal | Vellejo Game Air Chainmail Silver |
| Exhaust, Track Wash | Vallejo Model Color Cavalry Brown |
| Lights Green | Vallejo Model Color Green Fluo |
| Lights Red | Vallejo Game Color Bloody Red |

### Base

| PART | COLOR |
| --- | --- |
| Base | Vallejo Dark Earth Texture |
| Highlights | Vallejo Model Color Pale Grey |

### City Battlefield

Primer: Montana Gold Black

#### Buildings

* GW Zandri Dust
* Ammo of Mig: RAL 7028 Dunkelgelb aus'44 DGI A.MIG-011
* Drybrush Vallejo Bleached Bone

#### Building Rooftops

* Tamiya Hull Red XF-9
* Vallejo Model Color Cavalry Brown 70982
* Black Oil Wash

#### Metal Parts

* Vallejo Boltgun Metal
* GW Nuln Oil

#### Ruins
* Vallejo Model Color Dark Grey
* Vallejo Model Color Basalt Grey
* Vallejo Model Air Dark Earth 71.029

#### Flat Surfaces
* Vallejo Model Color Basalt Grey
* Vallejo Model Air Dark Earth 71.029
* Vallejo Polyurethane Primer Black

#### Crater
* Vallejo Model Air Dark Earth 71.029
* Minitare D6-114 Earth
* Vallejo Polyurethane Primer Black

#### Bunker & Weapon Emplacements
* Ammo of Mig: RAL6003 Olivgrün opt.2 A.MIG-002
* Ammo of Mig: RAL 6011 Resedragrün A.MIG-003

## Flames of War

### United States

### Infantry

Primer: Vallejo Acrylic-Polyurethane Grey Primer

| ITEM | BASE | SHADE | HIGHLIGHT 1 | HIGHLIGHT 2 |
| --- | --- | --- | --- | --- |
| Pants | VMC US Field Drab (873) | GW Agrax Earthshade |  |  |
| Jackets & Leggings | VMC Khaki (988) | GW Agrax Earthshade | VMC Khaki (988) |  |
| Flesh | GW Contrast Guilliman Flesh | GW Contrast Guilliman Flesh | GW Kislev Flesh |  |
| Webbing | VMC Green Grey (886) | GW Agrax Earthshade | VMC Green Grey (886) |  |
| Rifle Wood Base | VMC Flat Brown (984) | GW Agrax Earthshade | VMC Flat Brown (984) |  |
| Metal | VMC German Grey (995) | GW Nuln Oil | VMC German Grey (995) |  |
| Helmet | VMC Olive Drab (887) | GW Athonian Camoshade | VMC Olive Drab (887) |  |
| Boots & Holster | VMC Flat Brown (984) | GW Agrax Earthshade | VMC Flat Brown (984) | VMC Mahogany Brown (846) |

#### Bases

1. Vallejo Dark Earth Texture
2. GW Dryad Bark
3. VMC Green Ochre 70914
4. VGC Bonewhite 72034

## Force on Force

### USMC

Primer: Vallejo Primer Black Acrylic-Polyurethane (200ml)

Uniform:

* Vallejo Khaki
* Vallejo Stone Grey
* Vallejo Deck Tan
* GW Devlan Mud

Webbing:

* Vallejo English Uniform
* GW Devlan Mud
* Vallejo US Drab Earth

Goggles / Straps:

* Vallejo Iraqi Sand

Weapons:

* Vallejo Negro Black
* Vallejo German Grey

Base:

* Vallejo Desert Yellow

## Middle-earth Strategy Battle Game

### Rohan Defaults

Primer: Vallejo Polyurethane Grey Primer

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Flesh | GW Cadian Fleshtone | GW Contrast Guilliman Flesh | GW Cadian Fleshtone | GW Kislev Flesh |  |
| Blond hairs, beard | GW Zandri Dust | GW Agrax Earthshade | GW Zandri Dust | Vallejo Game Color Bonewhite 72.034 |
| Brown hairs, beard | GW Mournfang Brown | GW Agrax Earthshade | GW Skrag Brown |
| Metal | Vallejo Game Air Chainmal Silver 72.753 | GW Nuln Oil | Vallejo Game Air Chainmal Silver 72.753 | GW Chainmail (alte Farbe) |  |  |
| Wood | GW Dryad Bark | GW Agrax Eartshade | GW Gorthor Brown (thin lines) | Vallejo Model Color Tan Earth (thin lines) | GW Dryad Bark (Glaze) |
| Mantel 1 | GW Castellan Green | GW Athonian Camoshade | GW Castellan Green | GW Castellan Green & GW Straken Green (50/50) | GW Straken Green | GW Castellan Green Glaze |
| Mantel 2 | GW Caliban Green | GW Nuln Oil | GW Caliban Green | GW Caliban Green &GW Warpstone Glow (70/30) | GW Caliban Green &GW Warpstone Glow (30/70) | GW Warpstone |
| Gold ornaments | Vallejo Bright Bronze | GW Reikland Fleshshade | Vallejo Game Air Polished Gold 72.755 | GW Chainmail (old color) |
| Leder (rötlich) | GW Doombull Brown | GW Agrax Eartshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur |
| Leder (bräunlich) | GW Dryad Bark | GW Agrax Eartshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown |
| Saddle Wood | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown

### Rohan Horses

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Brown Horse 1 | GW Mournfang Brown | GW Skrag Brown | GW Skrag Brown & VJ White (70/30) | GW Agrax Earthshade |  |  |
| Brown Horse 2 | GW Rhinox Hide | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown & Tuskgor Fur (50/50) |  | Agrax Earthshade |
| Brown Horse 3 | GW Dryad Bark | GW Gorthor Brown | GW Agrax Earthshade |  |  |  |
| Black-brown Horse | VJ Primer Black | GW Dryad Bark | GW Nuln Oil |  |  | Mähne/Schweif schwarz, dann GW Dryad Bark trockenbürsten |
| White Horse | Vallejo Model Color Pale Grey | VMC White |  |  |  |  |
| Horse Blanket | GW Castellan Green | GW Athonian Camoshade | GW Castellan Green & GW Straken Green (50/50) |  GW Straken Green |  |  |
| Horse harness | GW Gorthor Brown | GW Agrax Earthshade | VMC Deck Tan | VGC Bonewhite |  |  |
| Head protection | GW Doombull Brown | GW Agrax Earthshade | GW Tuskor Fur |  |  |  |
| Hooves dark | VMC Basalt Grey | GW Contrast Wyldwood | VMC Basalt Grey | GW Agrax Earthshade (stark verdünnt) |  |  |
| Hooves light | VMC Deck Tan | Agrax Earthshade | VGC Bonewhite |  |  |  |
| Gold | Vallejo Game Color Bronze | GW Reikland Fleshshade | Vallejo Game Air Polished Gold 72.755 | GW Chainmail (alte Farbe) |  |  |
| Saddle | GW Dryad Bark | GW Agrax Earthshade |  |  |  |  |
| Black mane | GW Abaddon Black | VMC Basalt Grey | GW Nuln Oil | VMC Basalt Grey |  |  |
| Hazelnut brown mane | GW Mournfang Brown | GW Agrax Earthshade | GW Mournfang Brown | GW Skrag Brown | GW Skrag Brown & VGC Bonewhite (50/50) | VGC Bonewhite |
| Fetlock white | Daler Rowny White |  |  |  |  |  |
| Fetlock black | VGI Black |  |  |  |  |  |
| Eyes | GW Contrast Black Templar | Daler & Rowney White Ink | GW Abaddon Black |  |  |  |
| Inside of the mouth | GW Contrast Black Templar |  |  |  |  |  |
| Tongue | VGC Bloody Red & VMC Deck Tan (50/50) | VGC Bloody Red & VMC Deck Tan (25/75) |  |  |  |  |
| Teeth | VMC Deck Tan |  |  |  |  |  |

### Dernhelm

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Brown horse | GW Mournfang Brown | GW Skrag Brown | GW Skrag Brown & VJ White () | GW Agrax Earthshade |
| Shield | GW Caliban Green | GW Nuln Oil | GW Caliban Green | GW Caliban Green &GW Warpstone Glow (70/30) | GW Caliban | Green &GW Warpstone Glow (30/70) | GW Warpstone |
| Shield emblem | Vallejo Model Color  Deck Tan 70986 | Vertiefungen mit GW Agrax Earthshade | Game Air Dead White 72701 & Vallejo Model Color  Deck Tan 70986 (70/30) |
| Shield back |  | GW Agrax Eartshade (x 2) |
| Red leather | GW Doombull Brown | GW Agrax Eartshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur |
| Brown leather 1 | GW Dryad Bark | GW Agrax Eartshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown |
| Brown leather 2, Shirt | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown | GW Mournfang Brown & Skrag Brown (50/50) oder GW Rhinox Base & GW Mournfang Brown & Vallej MC Tan Earth (40/40/20) |
| Arrow quiver | GW Gorthor Brown | GW Agrax Eartshade | GW Gorthor Brown | GW Gorthor Brown & Vallejo MC Tan Earth (50/50) | Vallejo MC Tan Earth |

| Sword- / bowhilt | Vallejo Tan Earth | GW Agrax Eartshade | Vallejo Tan Earth | Vallejo Game Color Bonewhite 72.034 |
| Arrow feathers |  | GW Agrax Earthshade | Vallejo Model Color Deck Tan |
| Trousers | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & Vallejo Tan Earth (50/50) | GW Dryad Bark & Vallejo Tan Earth (15/85) |

### King Theoden

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III |
| --- | --- | --- | --- | --- | --- |
| Chain mail bronze | Vallejo Bright Bronze | GW Agrax Earthshade | Vallejo Bright Bronze |  |  |
| Leather armor (reddish), Gürtel, Riemen | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur |
| Sword hilt | Vallejo Tan Earth | GW Agrax Earthshade | Vallejo Tan Earth |  |  |
| Trousers, Shoes, Bag | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown |
| Shield wood | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown |  |


### Gamling

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Pferd braun 2 | GW Rhinox Hide | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown & Tuskgor Fur (50/50) |  | Agrax Earthshade
| Schild grün, Gürtelbund | Vorderseite mit GW Caliban Green (Emblem grau lassen) |  | GW Caliban Green & Vallejo Game Color Goblin Green 72030 (50/50) | Vallejo Game Color Goblin Green 72030 | Kante mit GW Nurgling Green
| Schild braun | Vorderseite mit GW Rhinox Hide  |  | GW Mournfang Brown | Kante mit GW Skrag Brown
| Schild rot | GW Mephiston Red |  | VGC Bloody Red
| Schildemblem | Vallejo Model Color  Deck Tan 70986 | Vertiefungen mit GW Agrax Earthshade | Game Air Dead White 72701 & Vallejo Model Color  Deck Tan 70986 (70/30)
| Schild Rückseite |  | GW Agrax Eartshade (x 2)
| Leder 2 (bräunlich), Hemd | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown | GW Mournfang Brown & Skrag Brown (50/50) oder GW Rhinox Base & GW Mournfang Brown & Vallej MC Tan Earth (40/40/20)
| Pfeilköcher | GW Gorthor Brown | GW Agrax Eartshade | GW Gorthor Brown | GW Gorthor Brown & Vallejo MC Tan Earth (50/50) | Vallejo MC Tan Earth
| Schwert- / Bogengriff | Vallejo Tan Earth | GW Agrax Eartshade | Vallejo Tan Earth | Vallejo Game Color Bonewhite 72.034
GW Caliban Green | GW Nuln Oil | GW Caliban Green | GW Caliban Green &GW Warpstone Glow (70/30) | GW Caliban Green &GW Warpstone Glow (30/70) | GW Warpstone | GW Castellan Green Glaze
| Pfeilfeder |  | GW Agrax Earthshade | Vallejo Model Color Deck Tan
| Hose | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & Vallejo Tan Earth (50/50) | GW Dryad Bark & Vallejo Tan Earth (15/85)

### Warriors & Riders of Rohan

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Schild grün, Gürtelbund | Vorderseite mit GW Caliban Green (Emblem grau lassen) |  | GW Caliban Green & Vallejo Game Color Goblin Green 72030 (50/50) | Vallejo Game Color Goblin Green 72030 | Kante mit GW Nurgling Green
| Schild braun | Vorderseite mit GW Rhinox Hide  |  | GW Mournfang Brown | Kante mit GW Skrag Brown
| Schild rot | GW Mephiston Red |  | VGC Bloody Red
| Schildemblem | Vallejo Model Color  Deck Tan 70986 | Vertiefungen mit GW Agrax Earthshade | Game Air Dead White 72701 & Vallejo Model Color  Deck Tan 70986 (70/30)
| Schild Rückseite |  | GW Agrax Eartshade (x 2)
| Leder 2 (bräunlich), Hemd | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown | GW Mournfang Brown & Skrag Brown (50/50) oder GW Rhinox Base & GW Mournfang Brown & Vallej MC Tan Earth (40/40/20)
| Pfeilköcher | GW Gorthor Brown | GW Agrax Eartshade | GW Gorthor Brown | GW Gorthor Brown & Vallejo MC Tan Earth (50/50) | Vallejo MC Tan Earth
| Schwert- / Bogengriff | Vallejo Tan Earth | GW Agrax Eartshade | Vallejo Tan Earth | Vallejo Game Color Bonewhite 72.034
| Pfeilfeder |  | GW Agrax Earthshade | Vallejo Model Color Deck Tan
| Hose | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & Vallejo Tan Earth (50/50) | GW Dryad Bark & Vallejo Tan | Earth (15/85)

### Hama

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
Leder 2 (bräunlich), Hemd | GW Rhinox Hide | GW Agrax Earthshade | GW Mournfang Brown | GW Skrag Brown
Schwert- / Bogengriff | Vallejo Tan Earth | GW Agrax Eartshade | Vallejo Tan Earth
Hose | GW Dryad Bark | GW Agrax Earthshade | GW Gorthor Brown
Arm- & Beinschoner Verzierungen | GW Doombull Brown | GW Agrax Eartshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur
Hemd, Gürtelband | GW Mephiston Red | GW Agrax Earthshade | GW Mephiston Red | VGC Bloody Red

### Royal Guard

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
Schild Vorderseite | GW Caliban Green | GW Nuln Oil | GW Caliban Green & Vallejo Game Color Goblin Green 72030 (50/50) | Vallejo Game Color Goblin Green 72030 | Kante mit GW Nurgling Green
Leder (bräunlich), Hose, Innenfutter | GW Dryad Bark | GW Agrax Eartshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown
Hemd, Gürtelband | GW Mephiston Red | GW Agrax Earthshade | GW Mephiston Red | VGC Bloody Red
Schulterleder, Gürtel, Rüstungshalterung, Handschuhe | GW Rhinox Hide | GW Agrax Earthshade | GW Doombull Brown | GW Tuskgor Fur
Pferdeschwanz | GW Abaddon Black |  | GW Dryad Bark
Schild Rückseite |  | GW Agrax Eartshade (x 3)
Schwertgriff | Vallejo Tan Earth | GW Agrax Eartshade | Vallejo Tan Earth | Vallejo Game Color Bonewhite 72.034
Arm- & Beinschoner Verzierungen | GW Doombull Brown | GW Agrax Eartshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur
Schwertgürtel und -scheide | GW Mournfang Brown | GW Agrax Earthshade | GW Mournfang Brown | GW Skrag Brown
Sattelholz | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown

### Grimbold & Helmingas

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
Schild | GW Castellan Green | GW Athonian Camoshade | GW Castellan Green | GW Castellan Green & GW Straken Green (50/50) | GW Straken Green | GW Castellan Green Glaze
Waffenrock | GW Dryad Bark | GW Agrax Eartshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown
Gürtel / Taschen / Ärmel | GW Mournfang Brown | GW Agrax Earthshade | GW Mournfang Brown
Arm- & Beinbandagen Braun | VMC Flat Earth | GW Agrax Eartshade | VMC Flat Earth | VMC Tan Earth | VMC Tan Earth & VMC Iraqui Sand (50/50) | VMC Iraqui Sand
Arm- & Beinbandagen Sand | VMC Tan Earth | GW Agrax Eartshade | VMC Tan Earth | VMC Iraqui Sand
Hose schwarz | GW Contrast Black Templar | VMC Basalt Grey | VMA Pale Grey | GW Contrast Black Templar & GW Technical Contrast Medium (10/90)
Fell | GW Dryad Bark | GW Agrax Eartshade | GW Gorthor Brown | VGC Bonewhite
Hemd (rötlich), Helm | GW Doombull Brown | GW Agrax Eartshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur
Horn | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & VMC Tan Earth (50/50) | VMC Tan Earth | VMC Deck Tan
Banner grün | GW Caliban Green | GW Nuln Oil | GW Caliban Green | GW Caliban Green &GW Warpstone Glow (70/30) | GW Caliban Green &GW Warpstone Glow (30/70) | GW Warpstone
Banner weiß | VMC Deck Tan | GW Nuln Oil | VMA White

### Eomer

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III |
| --- | --- | --- | --- | --- | --- |
| Flesh | GW Cadian Fleshtone | GW Contrast Guilliman Flesh | GW Cadian Fleshtone | GW Kislev Flesh
| Kettenhemd Bronze | Vallejo Bright Bronze | GW Agrax Earthshade | Vallejo Bright Bronze
| Lederrüstung (rötlich), Gürtel, Riemen | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur
| Schwertgriff | Vallejo Tan Earth | GW Agrax Earthshade | Vallejo Tan Earth
| Hose, Schuhe, Tasche | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown

### Theodred

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III |
| --- | --- | --- | --- | --- | --- |
Rüstung, Armschoner, Beinschoner Grün | GW Caliban Green | GW Nuln Oil | GW Caliban Green &GW Warpstone Glow (70/30) | GW Warpstone | GW Moot Green
Rüstung Einfassung | Vallejo Model Color Cavalry 70982 | GW Agrax Earthshade | GW Mephiston Red | Vallejo Game Color Bloody Red
Stiefel, Hose, Gürtel, Hemd | GW Dryad Bark | GW Agrax Earthshade | GW Dryad Bark & GW Gorthor Brown (60/40) | GW Gorthor Brown
Sattelholz | GW Rhinox Hide | GW Agrax Earthshade | GW Rhinox Hide & GW Mournfang Brown (50/50) | GW Mournfang Brown
Handschuhe, Rüstungshalterung, Schwertscheide | GW Rhinox Hide | GW Agrax Earthshade | GW Doombull Brown | GW Tuskgor Fur

### Farmer Maggot's Dogs

Primer: Vallejo Polyurethane Grey Primer

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
Schwarzes Fell | GW Contrast Black Templars (x2) |  |  |  |  |
Dunkelbraunes Fell | GW Dryad Bark & GW Mournfang Brown (25 % / 75 %) | GW Agrax Earthshade | GW Mournfang Brown & Vallejo Tan Earth (50/50) | GW Mournfang Brown & Vallejo Tan Earth (10/90) | Vallejo Tan Earth | Vallejo Tan Earth & Vallejo Iraqi Sand (50/50)
Halsband | GW Doombull Brown | GW Agrax Earthshade | GW Doombull Brown | GW Doombull Brown & GW Tuskor Fur (50/50) | GW Tuskor Fur |

### Rohan House

Primer: Vallejo Polyurethane Grey Primer

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II | HIGHLIGHT III | EXTRA |
| --- | --- | --- | --- | --- | --- | --- |
| Holz | VMC Basalt Grey (Airbrush) | VGC Stonewall Grey | VMC Deck Tan | VMA White | GW Contrast Skeleton Horde & GW Technical Contrast Medium (50/50) | GW Gryphonne Sepia / GW Agrax Earthshade /GW Athonian Camoshade | VGC Bonewhite |
| Metall | VMC Basalt Grey (Airbrush) | VGA Chainmail | GW Nuln Oil | GW Chainmail | Vallejo Pigments Brown Iron Oxide |  |
| Dach | VMC Basalt Grey (Airbrush) | GW Zandri Dust | VGC Bonewhite | GW Contrast Skeleton Horde | VGC Bonewhite |  |
| Gold | VMC Basalt Grey (Airbrush) | VGC Bright Bronze | GW Reikland Fleshshade | VGA Polished Gold | GW Chainmail |  |
| Tür | VMC Basalt Grey (Airbrush) | VMC Luftwaffe Camo Green | VMC Deck Tan | VMA White | GW Contrast Skeleton Horde & GW Technical Contrast Medium (50/50) | VGC Bonewhite |
| Pferdegeschirr | VMC Basalt Grey (Airbrush) | GW Gorthor Brown | GW Agrax Earthshade | GW Gorthor Brown |  |  |
| Fenster | VMC Basalt Grey (Airbrush) | GW Contrast Black Templar |  |  |  |  |
| Fenstergitter | VMC Basalt Grey (Airbrush) | VGA Chainmail | GW Contrast Black Templar | GW Chainmail |  |  |

### Bases

| PART | BASE | HIGHLIGHT I | HIGHLIGHT II |
| --- | --- | --- | --- |
| Earth | Vallejo Dark Earth Texture | GW Zandri Dust | Vallejo Iraqui Sand |
| Baserand | GW Abaddon Black |  |  |
| Tufts |  |  |  |
| Stones | Vallejo Basalt Grey | Vallejo Model Air Pale Grey | Vallejo Model Air White |

### Nazgul of Dol Guldur

Primer: Vallejo Polyurethane Black Primer

| ITEM | BASE | SHADE | HIGHLIGHT I | HIGHLIGHT II |
| --- | --- | --- | --- | --- |
| Clothes | Daler Rowney FW White | GW Biel-Tan Green |  |
| Metal | Vallejo Game Air Chainmail Silver | GW Nuln Oil | Vallejo Game Air Chainmail Silver | GW Chainmail |
| Base | VMC Basalt Grey, VMA Pale Grey, VMA Dark Earth |  |  |
